# Generated by Django 5.2.13 on 2026-04-30 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployments', '0001_initial'),
        ('people', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='deployed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments_made', to='people.employeeprofile'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='rolled_back_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollbacks', to='deployments.deployment'),
        ),
        migrations.AddField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='projects.project'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='deployments.environment'),
        ),
        migrations.AddField(
            model_name='release',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases_created', to='people.employeeprofile'),
        ),
        migrations.AddField(
            model_name='release',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='projects.project'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='deployments.release'),
        ),
        migrations.AlterUniqueTogether(
            name='environment',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('project', 'version')},
        ),
    ]
