# Generated by Django 5.2.13 on 2026-05-02 19:07

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_alter_contenttype_options_alter_contenttype_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
