# Generated by Django 5.2.13 on 2026-04-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('project_manager', 'Project Manager'), ('team_lead', 'Team Lead'), ('staff', 'Staff')], default='staff', max_length=30),
        ),
    ]
