# Generated by Django 5.2.13 on 2026-04-30 05:37

import django.contrib.admin.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='logentry',
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.AlterField(
            model_name='logentry',
            name='action_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='action time'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
